baseURL = 'https://sollecitom.github.io/software-product-development-blog/'
languageCode = 'en-us'
title = 'Michele on Software'
copyright = "Copyright © 2023 - Michele Sollecito"
canonifyURLs = true  # Review: Consider disabling if relative URLs are sufficient
summaryLength = 30
enableEmoji = true
theme = 'hugo-kiera'

# Menu configuration for main toolbar
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 1

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories"
weight = -1

# Pagination configuration
[pagination]
pagerSize = 5

# Taxonomies for author metadata
[taxonomies]
author = "author"

# Author configuration (optional, for backward compatibility)
[author]
name = "Michele Sollecito"

# Social media links
[params]
tagline = "My opinions about software product development"
customCSS = []
github = "sollecitom"
linkedin = "michelesollecito"
twitter = "sollecitom"
# instagram = "username"
# stackoverflow = "username"
# youtube = "user/username"
# devto = "username"
# utterancesRepo = "username/repository"
# utterancesIssueTerm = "pathname"
# homepageLength = 10
# commentAutoload = true
# mathjax = true
# katex = true
# google_fonts = ["Staatliches"]
# disableDarkModeCSS = false

# Disqus configuration (uncomment if needed)
[services.disqus]
shortname = "software-product-development-sollecitom"

# Google Analytics configuration (uncomment if needed)
# [services.googleAnalytics]
#   ID = "UA-XXXXX-Y"